# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TooDoo < Formula
  desc ""
  homepage "https://github.com/adityanagar10/too-doo"
  version "0.0.6"

  on_macos do
    url "https://github.com/includebitslabs/too-doo/releases/download/v0.0.6/too-doo_0.0.6_darwin_all.tar.gz"
    sha256 "ea8a8815df49a8a2cd27cfd66469ea301813c202e7c3e9bdb23cf9a7dea0270a"

    def install
      bin.install "too-doo"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/includebitslabs/too-doo/releases/download/v0.0.6/too-doo_0.0.6_linux_amd64.tar.gz"
      sha256 "4c97ec9a88f9250ba93f950c2d0dacba8f3067a28cde011127cad6da58131111"

      def install
        bin.install "too-doo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/includebitslabs/too-doo/releases/download/v0.0.6/too-doo_0.0.6_linux_arm64.tar.gz"
      sha256 "75deb2a186820e3b0b46dd5404fed45da0abe598234d5a9fbe30ed1196747369"

      def install
        bin.install "too-doo"
      end
    end
  end
end
