# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TooDoo < Formula
  desc ""
  homepage "https://github.com/adityanagar10/too-doo"
  version "0.0.1"

  on_macos do
    url "https://github.com/adityanagar10/too-doo/releases/download/v0.0.1/too-doo_0.0.1_darwin_all.tar.gz"
    sha256 "3aba3cd62a76529c62068efee48206b7248583e3b2bd77e78c9e27746a11860b"

    def install
      bin.install "too-doo"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/adityanagar10/too-doo/releases/download/v0.0.1/too-doo_0.0.1_linux_amd64.tar.gz"
      sha256 "e2e22562d230ccc38162a9b551e4f3155598eec923f10e4f36583eedad0f0a1f"

      def install
        bin.install "too-doo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adityanagar10/too-doo/releases/download/v0.0.1/too-doo_0.0.1_linux_arm64.tar.gz"
      sha256 "e3c425249d82e252df3f320bd6258099e5f428cd7aa3de60ed1da63b47579be9"

      def install
        bin.install "too-doo"
      end
    end
  end
end
